
SELECT DBO.fn_convert_time (1,'MINUTO','MICROSSEGUNDO')

SELECT DBO.fn_convert_time (360,'mes','ano')
GO

/*
-- FELIPE AGUIAR - 2021-11-27 --

Exemplo:
** Converter 1 Minuto para Microssegundos: **
SELECT DBO.fn_convert_time (1,'MINUTO','MICROSSEGUNDO')
** Converter 100 Anos para Seculo: **
SELECT DBO.fn_convert_time (100,'ANO','SECULO')

*/
ALTER function fn_convert_time 
(
	@valor NUMERIC(15,3), 
	@tipo_entrada varchar(50), 
	@tipo_SAIDA varchar(50)
)
returns VARCHAR(20)
begin

DECLARE @TABELA TABLE (ID INT, TIPO VARCHAR(50),VALOR_CONVERSAO NUMERIC(15,3))
INSERT INTO  @TABELA VALUES (1,'MICROSSEGUNDO',0)
INSERT INTO  @TABELA VALUES (2,'MILISSEGUNDO' ,1000 )
INSERT INTO  @TABELA VALUES (3,'SEGUNDO' ,1000 )
INSERT INTO  @TABELA VALUES (4,'MINUTO' ,60 )
INSERT INTO  @TABELA VALUES (5,'HORA' ,60 )
INSERT INTO  @TABELA VALUES (6,'DIA' ,24 )
INSERT INTO  @TABELA VALUES (7,'SEMANA' ,7 )
INSERT INTO  @TABELA VALUES (8,'MES' ,4.345 )
INSERT INTO  @TABELA VALUES (9,'ANO' ,12 )
INSERT INTO  @TABELA VALUES (10,'DECADA' ,10 )
INSERT INTO  @TABELA VALUES (11,'SECULO' ,10 )

DECLARE @ID_TIPO_ENTRADA INT, @ID_TIPO_SAIDA INT, @I INT = 0, @QNTD_CONVERSAO INT, @RETORNO VARCHAR(20)

SELECT @ID_TIPO_ENTRADA = ID
FROM @TABELA
WHERE TIPO = @tipo_entrada

SELECT @ID_TIPO_SAIDA = ID
FROM @TABELA
WHERE TIPO = @tipo_SAIDA

SELECT @QNTD_CONVERSAO = CASE WHEN @ID_TIPO_SAIDA > @ID_TIPO_ENTRADA THEN @ID_TIPO_SAIDA - @ID_TIPO_ENTRADA 
							  WHEN @ID_TIPO_ENTRADA > @ID_TIPO_SAIDA THEN @ID_TIPO_ENTRADA - @ID_TIPO_SAIDA END
							

WHILE @I < @QNTD_CONVERSAO
BEGIN 
	
	--EXEMPLO: HORA PARA MINUTO
	IF @ID_TIPO_ENTRADA > @ID_TIPO_SAIDA
	BEGIN
		SELECT @valor = (@valor * VALOR_CONVERSAO) --, id , (@ID_TIPO_ENTRADA - @I)
		FROM @TABELA
		WHERE ID = (@ID_TIPO_ENTRADA - @I)
	END
	
	--EXEMPLO: SEGUNDO PARA MINUTO 
	IF @ID_TIPO_ENTRADA < @ID_TIPO_SAIDA
	BEGIN
		
		SELECT @valor = (@valor / VALOR_CONVERSAO) 
		FROM @TABELA
		WHERE ID = (@ID_TIPO_ENTRADA + @I) +1
		order by ID
	END

	SET @I = @I +1 

END	
	 SELECT @RETORNO = @VALOR
	 SELECT @RETORNO = CASE WHEN RIGHT(@RETORNO,3) = 0
								THEN SUBSTRING(@RETORNO,1,CHARINDEX('.',@RETORNO,1)-1)
							WHEN RIGHT(@RETORNO,3) > 0 THEN @RETORNO
					  END

	RETURN @RETORNO 

end

